create database litshelf;
show databases;
use litshelf;
create table books(Book_id int auto_increment primary key not null,Title varchar(100) not null,Genre varchar(50) not null);
alter table books add Price varchar(10) not null;
insert into books(Title,Genre,Price) values("The Great Gatsby","Fiction",15.99),("Python Programming","Tech",45.50),("Pride and Prejudice","Fiction",12.99),("Data Science for Beginners","Tech",39.99),("The Hobbit","Fantasy",18.50),("1984","Fiction",14.99);
insert into books(Title,Genre,Price)values("The Catcher in the Rye","Fiction",13.99);
update books set price=49.99 where Book_id=2;
select * from books;
select * from books where Genre="Fiction";
select distinct Title from books;
select * from books where Price>10.00 and Price<20.00;
select * from books where Genre="Fiction" or Price=13.99;
select * from books order by Title asc;
select * from books order by Title desc;
select max(Price) from books;
select min(Price) from books;
select count(*) from books where Price>20.00;
select sum(Price) from books; 
select avg(Price) from books;
select Genre, count(*) from books group by Genre having count(*)>1;