create database kk;
show databases;
use kk;
create table student(Student_id int not null auto_increment,Student_name varchar(100) not null,Age int not null,Place varchar(100),primary key(student_id));
describe student;
insert into student(Student_name,Age,Place) values("Akhil",20,"Trivandrum"),("Manju",18,"Ernakulam"),("Shareef",13,"Palakad"),("Praveen",32,"Thrissur"),("John",20,"Trivandrum"),("Akhil",18,"Ernakulam"),("Aneesh",14,"Kottayam"),("Lakshmi",20,"Kozhikode"),("Cyril",12,"Ernakulam"),("Santosh",28,"Malapuram");
select *from student;  
alter table student add Course varchar(100)not null;
select *from student;
update student set course="BCA" where Student_id=1;
update student set course="CS" where Student_id=2;
update student set course="BCA" where Student_id=3;
update student set course="CS" where Student_id=4;
update student set course="CS" where Student_id=5;
update student set course="BCA" where Student_id=6;
update student set course="CS" where Student_id=7;
update student set course="BCA" where Student_id=8;
update student set course="BCA" where Student_id=9;
update student set course="CS" where Student_id=10;
select *from student;
alter table student change column Place Address varchar(100) not null;
select *from student; 
select Student_name from student;
update student set Student_name="Arun"where Student_id=3;
select *from student;
select *from student where Address="Ernakulam";
select *from student where Address="Ernakulam" or Age<18;
select distinct Student_name from student;
select distinct Address from student;
select *from student order by Student_name asc;
select *from student order by Student_name desc;
select count(*) from student where Address="Ernakulam";
alter table student add Marks varchar(100) not null ;
select * from student;
update student set Marks=30 where Student_id=1;
update student set Marks=50 where Student_id=2;
update student set Marks=57 where Student_id=3;
update student set Marks=70 where Student_id=4;
update student set Marks=79 where Student_id=5;
update student set Marks=80 where Student_id=6;
update student set Marks=70 where Student_id=7;
update student set Marks=90 where Student_id=8;
update student set Marks=95 where Student_id=9;
update student set Marks=78 where Student_id=10;
select *from student;